import type { Metadata } from 'next';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className="min-h-screen antialiased">
        <div className="p-sm mx-auto max-w-[1280px]">{children}</div>
      </body>
    </html>
  );
}
